doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
              string_functions:
                group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
                
              numeric_functions:
                rand: DoctrineExtensions\Query\Mysql\Rand

        second_level_cache:
           #enabled: true
           #regions:
           #     global:
           #         lifetime: 900
           #         cache_driver:
           #             type: memcache
           #             host: localhost
           #             port: 11211
                
                        
        #query_cache_driver:
        #    type: memcache
        #    host: localhost
        #    port: 11211
        #    instance_class: Memcache
        
        #result_cache_driver:
        #    type: memcache
        #    host: localhost
        #    port: 11211
        #    instance_class: Memcache