fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\Users
    from_email:
        address: "lamzin.an@gmail.com"
        sender_name: "lamzin.an@gmail.com"
    profile:
        form:
            type: App\Form\ProfileFormType