fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\Users
    from_email:
        address: '%env(resolve:ADMIN_EMAIL)%'
        sender_name: '%env(resolve:ADMIN_EMAIL)%'
    profile:
        form:
            type: App\Form\ProfileFormType
            
    registration:
        form:
            type: App\Form\RegistrationFormType
        confirmation:
            enabled: true