twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # Это один из вариантов сделать видимым в twig шаблоне значение из конфига (app.city_zero_id) определена в services.yaml
    globals:
      #city_zero_id: "%app.city_zero_id%"
      title: Default title
      additionalCss: ''
      sLocationUrl: '/'
      sFilterQueryString: ''
      h1: 'Заказ Газели в любом городе России'
      isAgreementPage: false
      politicDoc: /images/Politika_zashity_i_obrabotki_personalnyh_dannyh_2019-08-14.doc
      admin_phone: 8 918 735 36 57