#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_resetting_request:
    path: /remind
    defaults: { _controller: 'App\Controller\ResettingController::requestAction' }
    
fos_user_security_login:
    path: /login
    defaults: { _controller: 'fos_user.security.controller:loginAction' }
    
fos_user_resetting_send_email:
    path: /send-email
    defaults: { _controller: 'fos_user.resetting.controller:sendEmailAction' }
    
fos_user_resetting_reset:
    path: /resetting/reset/{token}
    defaults: { _controller: 'fos_user.resetting.controller:resetAction' }

fos_user_resetting_check_email:
    path: /resetting/check-email
    defaults: { _controller: 'fos_user.resetting.controller:checkEmailAction' }
    
fos_user_security_logout:
    path: /logout
    defaults: { _controller: 'fos_user.security.controller:logoutAction' }

fos_user_profile_show:
    path: /profile
    defaults: { _controller: 'fos_user.profile.controller:showAction' }

fos_user_profile_edit:
    path: /profile/edit
    defaults: { _controller: 'fos_user.profile.controller:editAction' }

fos_user_security_check:
    path: /login_check
    defaults: { _controller: 'fos_user.security.controller:checkAction' }
    