# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  #Adverts per page
  app.records_per_page: 20

  # Каждое объявление относится к какому-то населенному пункту. Населенный пункт обычно задается id города,
  #  а город имеет id региона в таблце cities.
  # Однако, в таблице regions существуют особые регионы, которые не регионы, а крупные города.
  # (Это сделано для более простого их показа в списке регионов и выбора из этого списка)
  # Для таких объявлений main.city был 0
  # Symfony требует установку отношений oneToMany, manyToOne 
  # Однако обновить схему базы данных невозможно, если существуют в main записи с city = 0
  # Для этого добавлен специальный город Скрытенбург, его id в базе разработчика 6362
  # Все main.city == 0 заменены на 6326
  # Приложение будет обрабатывать этот main.city так, как раньше обрабатывало 0
  # В базе на продакшене значение может быть иным.
  app.city_zero_id: 6326

  # Site Display Name
  app.site_name: 'Gazel Symfony 3.4 Demo'
  
  # Site domain
  app.domain: '%env(resolve:HOST)%'
  
  # Ключи для re-captcha
  app.google_recaptcha_site_key: '%env(resolve:GOOGLE_RECAPTCHA_SITEKEY)%'
  app.google_recaptcha_secret_key: '%env(resolve:GOOGLE_RECAPTCHA_SECRETKEY)%'

  # Ключи для отправки sms
  app.smspilotkey: '%env(resolve:SMSPILOTKEY)%'
  app.smspilot_sendername: '%env(resolve:SMSPILOT_SENDERNAME)%'
  # Интервал между возможностью отпарвки сообщений
  app.sms_interval: 63
  # Надо ли вообще отправлять sms
  app.sms_service_on: true


  #Включена ли вообще re-captcha
  app.google_recaptcha_on: '%env(resolve:GOOGLE_RECAPTCHA_ON)%'
  #app.google_recaptcha_on: '%env(resolve:GOOGLE_RECAPTCHA_ON)%'
  
  #Каталог с загружаемыми файлами
  app.uploadfiledir: 'images'

  # Реквизиты платежных систем

  # Яндекс деньги
  app.yamoney_number: '%env(resolve:YAMONEY_NUMBER)%'
  app.yamoney_key: '%env(resolve:YAMONEY_KEY)%'

  # Система тестирования
  test:
      phone: '80001112233'
      email: 'ftest_user@host.do'
      password: '123456aA'
      wrong_password: '1234567Aa'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    app.security.authentication_handler:
        class: App\Handler\AuthenticationHandler
        public: false
        arguments: ["@router", "@service_container"]

    app.security.logout_handler:
        class: App\Handler\LogoutHandler
        public: false
        arguments: ["@service_container"]
        
    # app/config/services.yml
    
    App\EventListener\ControllerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

            
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #app.twig_extension:
    #        class: App\Twig\GazelmeExtension
    #        arguments: ["@service_container"]
    #        tags:
    #            - { name: twig.extension, priority: 255 }
    
    # it work!
    App\Controller\ResettingController:
      decorates: fos_user.resetting.controller
      arguments:
        - '@App\Controller\ResettingController.inner'
        - '@event_dispatcher'
        - '@fos_user.resetting.form.factory'
        - '@fos_user.user_manager'
        - '@fos_user.util.token_generator'
        - '@fos_user.mailer'
        - '%fos_user.resetting.retry_ttl%'
        - '@service_container'



    App\Controller\ProfileController:
        decorates: fos_user.profile.controller
        arguments:
            - '@App\Controller\ProfileController.inner'
            - '@event_dispatcher'
            - '@fos_user.profile.form.factory'
            - '@fos_user.user_manager'
            - '@service_container'
            
    App\Controller\RegistrationController:
        decorates: fos_user.registration.controller
        arguments:
            - '@App\Controller\RegistrationController.inner'
            - '@event_dispatcher'
            - '@fos_user.registration.form.factory'
            - '@fos_user.user_manager'
            - '@security.token_storage'
            - '@service_container'

  
    app.form.profile:
        class: App\Form\ProfileFormType
        tags:
            - { name: form.type, alias: app_user_profile }
            
    app.form.registration:
        class: App\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }


# Это один из вариантов сделать видимым в twig шаблоне значение из конфига (app.city_zero_id) определена выше
# Это можно перенести в config/packages/twig.yaml
twig:
  globals:
    city_zero_id: "%app.city_zero_id%"
    recapcthasitekey: "%app.google_recaptcha_site_key%"
    google_recaptcha_on: "%app.google_recaptcha_on%"
    redirectToConfirmPhone: "0"
    yamoney_number: "%app.yamoney_number%"
    yamoney_key: "%app.yamoney_key%"
    site_name: "%app.site_name%"


